import './globals.css'
import { Footer } from '@/composites/Footer'
import { Header } from '@/composites/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='flex flex-col min-h-screen'>
          <Header />
          <div className='flex-grow'>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
